spring:
  datasource:
    url: jdbc:mariadb://localhost:7306/karif 
    username: root
    password: example
    driver-class-name: org.mariadb.jdbc.Driver
  mybatis:
    mapper-locations: classpath*:/mapper/**/*.xml
    mapper-scan: karif.system.mapper
  profiles:
    active: dev